### ISSUE TITLE
招待メールが送信できない問題を解決する

### ISSUE THREAD

**Issue by sakakendo0321** [teamET/2018.perform#19]

**Comment by sakakendo0321** [comment]
```
[2018-07-22 03:14:02] WARN Error sending email: Failed to send email. Reason: Can't send mail - all recipients were rejected. Please check your email settings andresend the invitation.
ERROR [2018-07-22 03:14:02] "POST /ghost/api/v0.1/invites/" 500 3001ms

NAME: EmailError
MESSAGE: Error sending email: Failed to send email. Reason: Can't send mail - all recipients were rejected. Please check your email settings and resend the invitation.

level:normal

Please see http://docs.ghost.org/v1/docs/mail-config for instructions on configuring email.
EmailError: Error sending email: Failed to send email. Reason: Can't send mail - all recipients were rejected. Please check your email settings and resend the invitation.
    at EmailError.GhostError (/var/lib/ghost/versions/1.24.9/core/server/lib/common/errors.js:9:26)
    at new EmailError (/var/lib/ghost/versions/1.24.9/core/server/lib/common/errors.js:45:20)
    at EventEmitter.<anonymous> (/var/lib/ghost/versions/1.24.9/core/server/services/mail/GhostMailer.js:104:31)
    at EventEmitter.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at DirectMailer.<anonymous> (/var/lib/ghost/versions/1.24.9/node_modules/directmail/lib/mailer.js:185:42)
    at SMTPClient.<anonymous> (/var/lib/ghost/versions/1.24.9/node_modules/directmail/lib/mailer.js:277:9)
    at SMTPClient.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at SMTPClient.emit (events.js:188:7)
    at SMTPClient._onError (/var/lib/ghost/versions/1.24.9/node_modules/simplesmtp/lib/client.js:373:10)
    at SMTPClient._actionRCPT (/var/lib/ghost/versions/1.24.9/node_modules/simplesmtp/lib/client.js:1054:18)
    at SMTPClient._onData (/var/lib/ghost/versions/1.24.9/node_modules/simplesmtp/lib/client.js:354:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

**Comment by sakakendo0321** [comment]
~/2018.perform/workspace/ghost$ cat config.development.json
{
  "url": "http://localhost:2368/",
  "server": {
    "port": 2368,
    "host": "127.0.0.1"
  },
  "database": {
    "client": "sqlite3",
    "connection": {
      "filename": "/home/xxxxx/2018.perform/workspace/ghost/content/data/ghost-local.db"
    }
  },
  "mail": {
        "tranport":"SMTP",
        "options":{
                "service":"Mailgun",
                "auth":{
                        "user":"postmaster@sandboxxxxxxxxxxxxxxxxxxxxxxxxmailgun.org",
                        "pass":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                }
        }
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "local",
  "paths": {
    "contentPath": "/home/xxxxx/2018.perform/workspace/ghost/content"
  }
}

**Comment by sakakendo0321** [comment]
> Failed to send email. Reason: Message delivery failed: 554 Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings..

**Comment by sakakendo0321** [comment]
development.jsonにsandboxの ` Default SMTP Login` と` Default Password `を入力して
sandboxのAuthorized Recipientsをしないといけないみたいだった
